/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_platanios_tensorflow_horovod_Horovod__ */

#ifndef _Included_org_platanios_tensorflow_horovod_Horovod__
#define _Included_org_platanios_tensorflow_horovod_Horovod__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_platanios_tensorflow_horovod_Horovod__
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_horovod_Horovod_00024_init
  (JNIEnv *, jobject);

/*
 * Class:     org_platanios_tensorflow_horovod_Horovod__
 * Method:    rank
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_org_platanios_tensorflow_horovod_Horovod_00024_rank
  (JNIEnv *, jobject);

/*
 * Class:     org_platanios_tensorflow_horovod_Horovod__
 * Method:    localRank
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_org_platanios_tensorflow_horovod_Horovod_00024_localRank
  (JNIEnv *, jobject);

/*
 * Class:     org_platanios_tensorflow_horovod_Horovod__
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_org_platanios_tensorflow_horovod_Horovod_00024_size
  (JNIEnv *, jobject);

/*
 * Class:     org_platanios_tensorflow_horovod_Horovod__
 * Method:    localSize
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_org_platanios_tensorflow_horovod_Horovod_00024_localSize
  (JNIEnv *, jobject);

/*
 * Class:     org_platanios_tensorflow_horovod_Horovod__
 * Method:    mpiThreadsSupported
 * Signature: ()I
 */
JNIEXPORT int JNICALL Java_org_platanios_tensorflow_horovod_Horovod_00024_mpiThreadsSupported
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
