/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_platanios_tensorflow_jni_TensorFlow__ */

#ifndef _Included_org_platanios_tensorflow_jni_TensorFlow__
#define _Included_org_platanios_tensorflow_jni_TensorFlow__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_platanios_tensorflow_jni_TensorFlow__
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_platanios_tensorflow_jni_TensorFlow_00024_version
  (JNIEnv *, jobject);

/*
 * Class:     org_platanios_tensorflow_jni_TensorFlow__
 * Method:    dataTypeSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_platanios_tensorflow_jni_TensorFlow_00024_dataTypeSize
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
