/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_platanios_tensorflow_jni_Session__ */

#ifndef _Included_org_platanios_tensorflow_jni_Session__
#define _Included_org_platanios_tensorflow_jni_Session__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_platanios_tensorflow_jni_Session__
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Session_00024_allocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Session__
 * Method:    delete
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Session_00024_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Session__
 * Method:    run
 * Signature: (J[B[J[J[I[J[I[JZ[J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_platanios_tensorflow_jni_Session_00024_run
  (JNIEnv *, jobject, jlong, jbyteArray, jlongArray, jlongArray, jintArray, jlongArray, jintArray, jlongArray, jboolean, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
