/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_platanios_tensorflow_jni_Tensor__ */

#ifndef _Included_org_platanios_tensorflow_jni_Tensor__
#define _Included_org_platanios_tensorflow_jni_Tensor__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    allocate
 * Signature: (I[JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_allocate
  (JNIEnv *, jobject, jint, jlongArray, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    fromBuffer
 * Signature: (I[JJL)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_fromBuffer
  (JNIEnv *, jobject, jint, jlongArray, jlong, jobject);

///*
// * Class:     org_platanios_tensorflow_jni_Tensor__
// * Method:    fromBuffer
// * Signature: (LI[JJ)J
// */
//JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_fromBuffer
//  (JNIEnv *, jobject, jobject, jint, jlongArray, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    dataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_dataType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    shape
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_shape
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_buffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    getEncodedStringSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_getEncodedStringSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    setStringBytes
 * Signature: ([BL)I
 */
JNIEXPORT jint JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_setStringBytes
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    getStringBytes
 * Signature: (L)V
 */
JNIEXPORT jbyteArray JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_getStringBytes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerAllocateContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerAllocateContext
  (JNIEnv *, jobject);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerDeleteContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerDeleteContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerAllocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerAllocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerDataType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerDataType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerShape
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerShape
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerDevice
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerDevice
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerDelete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerResolve
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerResolve
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerCopyToDevice
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerCopyToDevice
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerAllocateOp
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerAllocateOp
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerDeleteOp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerDeleteOp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpDevice
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpDevice
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerOpAddInput
 * Signature: (JJ);V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerOpAddInput
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrString
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrString
  (JNIEnv *, jobject, jlong, jstring, jbyteArray);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrStringList
 * Signature: (JLjava/lang/String;[L)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrStringList
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrInt
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrInt
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrIntList
 * Signature: (JLjava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrIntList
  (JNIEnv *, jobject, jlong, jstring, jlongArray);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrFloat
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrFloat
  (JNIEnv *, jobject, jlong, jstring, jfloat);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrFloatList
 * Signature: (JLjava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrFloatList
  (JNIEnv *, jobject, jlong, jstring, jfloatArray);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrBool
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrBool
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrBoolList
 * Signature: (JLjava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrBoolList
  (JNIEnv *, jobject, jlong, jstring, jbooleanArray);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrType
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrType
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrTypeList
 * Signature: (JLjava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrTypeList
  (JNIEnv *, jobject, jlong, jstring, jintArray);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrTensor
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrTensor
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrTensorList
 * Signature: (JLjava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrTensorList
  (JNIEnv *, jobject, jlong, jstring, jlongArray);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrShape
 * Signature: (JLjava/lang/String;[JI)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrShape
  (JNIEnv *, jobject, jlong, jstring, jlongArray, jint);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerSetOpAttrShapeList
 * Signature: (JLjava/lang/String;[J[II)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerSetOpAttrShapeList
  (JNIEnv *, jobject, jlong, jstring, jobjectArray, jintArray, jint);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    eagerExecuteOp
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_eagerExecuteOp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    cast
 * Signature: (LJJI)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_cast
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    pack
 * Signature: (LJ[JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_pack
  (JNIEnv *, jobject, jlong, jlongArray, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    stridedSlice
 * Signature: (LJJJJJJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_stridedSlice
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    reshape
 * Signature: (LJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_reshape
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Tensor__
 * Method:    add
 * Signature: (LJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Tensor_00024_add
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
