FROM ubuntu:18.04

# Copy and run the install script.
COPY .circleci/images/install.sh /install.sh
ARG DEBIAN_FRONTEND=noninteractive
RUN /install.sh

# Set up MPI
ENV TF_NEED_MPI 1

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

# COPY . /tensorflow_scala
