/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_platanios_tensorflow_jni_Function__ */

#ifndef _Included_org_platanios_tensorflow_jni_Function__
#define _Included_org_platanios_tensorflow_jni_Function__
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_platanios_tensorflow_jni_Function__
 * Method:    graphToFunction
 * Signature: (JLjava/lang/String;Z[J[J[I[J[I[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Function_00024_graphToFunction
  (JNIEnv *, jobject, jlong, jstring, jboolean, jlongArray, jlongArray, jintArray, jlongArray, jintArray, jobjectArray);

/*
 * Class:     org_platanios_tensorflow_jni_Function__
 * Method:    copyToGraph
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Function_00024_copyToGraph
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Function__
 * Method:    toFunctionDef
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_platanios_tensorflow_jni_Function_00024_toFunctionDef
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Function__
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Function_00024_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
