/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_platanios_tensorflow_jni_Server__ */

#ifndef _Included_org_platanios_tensorflow_jni_Server__
#define _Included_org_platanios_tensorflow_jni_Server__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_platanios_tensorflow_jni_Server__
 * Method:    newServer
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_platanios_tensorflow_jni_Server_00024_newServer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_platanios_tensorflow_jni_Server__
 * Method:    target
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_platanios_tensorflow_jni_Server_00024_target
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Server__
 * Method:    startServer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Server_00024_startServer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Server__
 * Method:    stopServer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Server_00024_stopServer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Server__
 * Method:    joinServer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Server_00024_joinServer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_platanios_tensorflow_jni_Server__
 * Method:    deleteServer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_platanios_tensorflow_jni_Server_00024_deleteServer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
