// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/lite/toco/model_flags.proto

#ifndef PROTOBUF_INCLUDED_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto
#define PROTOBUF_INCLUDED_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/contrib/lite/toco/types.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto 

namespace protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto
namespace toco {
class ArraysExtraInfo;
class ArraysExtraInfoDefaultTypeInternal;
extern ArraysExtraInfoDefaultTypeInternal _ArraysExtraInfo_default_instance_;
class ArraysExtraInfo_Entry;
class ArraysExtraInfo_EntryDefaultTypeInternal;
extern ArraysExtraInfo_EntryDefaultTypeInternal _ArraysExtraInfo_Entry_default_instance_;
class InputArray;
class InputArrayDefaultTypeInternal;
extern InputArrayDefaultTypeInternal _InputArray_default_instance_;
class InputArrayShape;
class InputArrayShapeDefaultTypeInternal;
extern InputArrayShapeDefaultTypeInternal _InputArrayShape_default_instance_;
class ModelFlags;
class ModelFlagsDefaultTypeInternal;
extern ModelFlagsDefaultTypeInternal _ModelFlags_default_instance_;
class ModelFlags_ModelCheck;
class ModelFlags_ModelCheckDefaultTypeInternal;
extern ModelFlags_ModelCheckDefaultTypeInternal _ModelFlags_ModelCheck_default_instance_;
class RnnState;
class RnnStateDefaultTypeInternal;
extern RnnStateDefaultTypeInternal _RnnState_default_instance_;
}  // namespace toco
namespace google {
namespace protobuf {
template<> ::toco::ArraysExtraInfo* Arena::CreateMaybeMessage<::toco::ArraysExtraInfo>(Arena*);
template<> ::toco::ArraysExtraInfo_Entry* Arena::CreateMaybeMessage<::toco::ArraysExtraInfo_Entry>(Arena*);
template<> ::toco::InputArray* Arena::CreateMaybeMessage<::toco::InputArray>(Arena*);
template<> ::toco::InputArrayShape* Arena::CreateMaybeMessage<::toco::InputArrayShape>(Arena*);
template<> ::toco::ModelFlags* Arena::CreateMaybeMessage<::toco::ModelFlags>(Arena*);
template<> ::toco::ModelFlags_ModelCheck* Arena::CreateMaybeMessage<::toco::ModelFlags_ModelCheck>(Arena*);
template<> ::toco::RnnState* Arena::CreateMaybeMessage<::toco::RnnState>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace toco {

// ===================================================================

class InputArrayShape : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toco.InputArrayShape) */ {
 public:
  InputArrayShape();
  virtual ~InputArrayShape();

  InputArrayShape(const InputArrayShape& from);

  inline InputArrayShape& operator=(const InputArrayShape& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InputArrayShape(InputArrayShape&& from) noexcept
    : InputArrayShape() {
    *this = ::std::move(from);
  }

  inline InputArrayShape& operator=(InputArrayShape&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InputArrayShape& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InputArrayShape* internal_default_instance() {
    return reinterpret_cast<const InputArrayShape*>(
               &_InputArrayShape_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InputArrayShape* other);
  friend void swap(InputArrayShape& a, InputArrayShape& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InputArrayShape* New() const final {
    return CreateMaybeMessage<InputArrayShape>(NULL);
  }

  InputArrayShape* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InputArrayShape>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InputArrayShape& from);
  void MergeFrom(const InputArrayShape& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputArrayShape* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 dims = 2;
  int dims_size() const;
  void clear_dims();
  static const int kDimsFieldNumber = 2;
  ::google::protobuf::int32 dims(int index) const;
  void set_dims(int index, ::google::protobuf::int32 value);
  void add_dims(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      dims() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_dims();

  // @@protoc_insertion_point(class_scope:toco.InputArrayShape)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > dims_;
  friend struct ::protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InputArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toco.InputArray) */ {
 public:
  InputArray();
  virtual ~InputArray();

  InputArray(const InputArray& from);

  inline InputArray& operator=(const InputArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InputArray(InputArray&& from) noexcept
    : InputArray() {
    *this = ::std::move(from);
  }

  inline InputArray& operator=(InputArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InputArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InputArray* internal_default_instance() {
    return reinterpret_cast<const InputArray*>(
               &_InputArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(InputArray* other);
  friend void swap(InputArray& a, InputArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InputArray* New() const final {
    return CreateMaybeMessage<InputArray>(NULL);
  }

  InputArray* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InputArray>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InputArray& from);
  void MergeFrom(const InputArray& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .toco.InputArrayShape shape = 6;
  bool has_shape() const;
  void clear_shape();
  static const int kShapeFieldNumber = 6;
  private:
  const ::toco::InputArrayShape& _internal_shape() const;
  public:
  const ::toco::InputArrayShape& shape() const;
  ::toco::InputArrayShape* release_shape();
  ::toco::InputArrayShape* mutable_shape();
  void set_allocated_shape(::toco::InputArrayShape* shape);

  // optional float mean_value = 3;
  bool has_mean_value() const;
  void clear_mean_value();
  static const int kMeanValueFieldNumber = 3;
  float mean_value() const;
  void set_mean_value(float value);

  // optional .toco.IODataType data_type = 5;
  bool has_data_type() const;
  void clear_data_type();
  static const int kDataTypeFieldNumber = 5;
  ::toco::IODataType data_type() const;
  void set_data_type(::toco::IODataType value);

  // optional float std_value = 4 [default = 1];
  bool has_std_value() const;
  void clear_std_value();
  static const int kStdValueFieldNumber = 4;
  float std_value() const;
  void set_std_value(float value);

  // @@protoc_insertion_point(class_scope:toco.InputArray)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_shape();
  void clear_has_shape();
  void set_has_mean_value();
  void clear_has_mean_value();
  void set_has_std_value();
  void clear_has_std_value();
  void set_has_data_type();
  void clear_has_data_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::toco::InputArrayShape* shape_;
  float mean_value_;
  int data_type_;
  float std_value_;
  friend struct ::protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RnnState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toco.RnnState) */ {
 public:
  RnnState();
  virtual ~RnnState();

  RnnState(const RnnState& from);

  inline RnnState& operator=(const RnnState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RnnState(RnnState&& from) noexcept
    : RnnState() {
    *this = ::std::move(from);
  }

  inline RnnState& operator=(RnnState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RnnState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RnnState* internal_default_instance() {
    return reinterpret_cast<const RnnState*>(
               &_RnnState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RnnState* other);
  friend void swap(RnnState& a, RnnState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RnnState* New() const final {
    return CreateMaybeMessage<RnnState>(NULL);
  }

  RnnState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RnnState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RnnState& from);
  void MergeFrom(const RnnState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RnnState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string state_array = 1;
  bool has_state_array() const;
  void clear_state_array();
  static const int kStateArrayFieldNumber = 1;
  const ::std::string& state_array() const;
  void set_state_array(const ::std::string& value);
  #if LANG_CXX11
  void set_state_array(::std::string&& value);
  #endif
  void set_state_array(const char* value);
  void set_state_array(const char* value, size_t size);
  ::std::string* mutable_state_array();
  ::std::string* release_state_array();
  void set_allocated_state_array(::std::string* state_array);

  // optional string back_edge_source_array = 2;
  bool has_back_edge_source_array() const;
  void clear_back_edge_source_array();
  static const int kBackEdgeSourceArrayFieldNumber = 2;
  const ::std::string& back_edge_source_array() const;
  void set_back_edge_source_array(const ::std::string& value);
  #if LANG_CXX11
  void set_back_edge_source_array(::std::string&& value);
  #endif
  void set_back_edge_source_array(const char* value);
  void set_back_edge_source_array(const char* value, size_t size);
  ::std::string* mutable_back_edge_source_array();
  ::std::string* release_back_edge_source_array();
  void set_allocated_back_edge_source_array(::std::string* back_edge_source_array);

  // optional int32 size = 3;
  bool has_size() const;
  void clear_size();
  static const int kSizeFieldNumber = 3;
  ::google::protobuf::int32 size() const;
  void set_size(::google::protobuf::int32 value);

  // optional bool discardable = 5;
  bool has_discardable() const;
  void clear_discardable();
  static const int kDiscardableFieldNumber = 5;
  bool discardable() const;
  void set_discardable(bool value);

  // @@protoc_insertion_point(class_scope:toco.RnnState)
 private:
  void set_has_state_array();
  void clear_has_state_array();
  void set_has_back_edge_source_array();
  void clear_has_back_edge_source_array();
  void set_has_discardable();
  void clear_has_discardable();
  void set_has_size();
  void clear_has_size();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr state_array_;
  ::google::protobuf::internal::ArenaStringPtr back_edge_source_array_;
  ::google::protobuf::int32 size_;
  bool discardable_;
  friend struct ::protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ArraysExtraInfo_Entry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toco.ArraysExtraInfo.Entry) */ {
 public:
  ArraysExtraInfo_Entry();
  virtual ~ArraysExtraInfo_Entry();

  ArraysExtraInfo_Entry(const ArraysExtraInfo_Entry& from);

  inline ArraysExtraInfo_Entry& operator=(const ArraysExtraInfo_Entry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArraysExtraInfo_Entry(ArraysExtraInfo_Entry&& from) noexcept
    : ArraysExtraInfo_Entry() {
    *this = ::std::move(from);
  }

  inline ArraysExtraInfo_Entry& operator=(ArraysExtraInfo_Entry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ArraysExtraInfo_Entry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArraysExtraInfo_Entry* internal_default_instance() {
    return reinterpret_cast<const ArraysExtraInfo_Entry*>(
               &_ArraysExtraInfo_Entry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ArraysExtraInfo_Entry* other);
  friend void swap(ArraysExtraInfo_Entry& a, ArraysExtraInfo_Entry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArraysExtraInfo_Entry* New() const final {
    return CreateMaybeMessage<ArraysExtraInfo_Entry>(NULL);
  }

  ArraysExtraInfo_Entry* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArraysExtraInfo_Entry>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ArraysExtraInfo_Entry& from);
  void MergeFrom(const ArraysExtraInfo_Entry& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArraysExtraInfo_Entry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string name_regexp = 7;
  bool has_name_regexp() const;
  void clear_name_regexp();
  static const int kNameRegexpFieldNumber = 7;
  const ::std::string& name_regexp() const;
  void set_name_regexp(const ::std::string& value);
  #if LANG_CXX11
  void set_name_regexp(::std::string&& value);
  #endif
  void set_name_regexp(const char* value);
  void set_name_regexp(const char* value, size_t size);
  ::std::string* mutable_name_regexp();
  ::std::string* release_name_regexp();
  void set_allocated_name_regexp(::std::string* name_regexp);

  // optional .toco.InputArrayShape shape = 5;
  bool has_shape() const;
  void clear_shape();
  static const int kShapeFieldNumber = 5;
  private:
  const ::toco::InputArrayShape& _internal_shape() const;
  public:
  const ::toco::InputArrayShape& shape() const;
  ::toco::InputArrayShape* release_shape();
  ::toco::InputArrayShape* mutable_shape();
  void set_allocated_shape(::toco::InputArrayShape* shape);

  // optional double min = 2;
  bool has_min() const;
  void clear_min();
  static const int kMinFieldNumber = 2;
  double min() const;
  void set_min(double value);

  // optional double max = 3;
  bool has_max() const;
  void clear_max();
  static const int kMaxFieldNumber = 3;
  double max() const;
  void set_max(double value);

  // optional .toco.IODataType data_type = 4;
  bool has_data_type() const;
  void clear_data_type();
  static const int kDataTypeFieldNumber = 4;
  ::toco::IODataType data_type() const;
  void set_data_type(::toco::IODataType value);

  // optional float constant_float_value = 6;
  bool has_constant_float_value() const;
  void clear_constant_float_value();
  static const int kConstantFloatValueFieldNumber = 6;
  float constant_float_value() const;
  void set_constant_float_value(float value);

  // @@protoc_insertion_point(class_scope:toco.ArraysExtraInfo.Entry)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_name_regexp();
  void clear_has_name_regexp();
  void set_has_min();
  void clear_has_min();
  void set_has_max();
  void clear_has_max();
  void set_has_data_type();
  void clear_has_data_type();
  void set_has_shape();
  void clear_has_shape();
  void set_has_constant_float_value();
  void clear_has_constant_float_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr name_regexp_;
  ::toco::InputArrayShape* shape_;
  double min_;
  double max_;
  int data_type_;
  float constant_float_value_;
  friend struct ::protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ArraysExtraInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toco.ArraysExtraInfo) */ {
 public:
  ArraysExtraInfo();
  virtual ~ArraysExtraInfo();

  ArraysExtraInfo(const ArraysExtraInfo& from);

  inline ArraysExtraInfo& operator=(const ArraysExtraInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArraysExtraInfo(ArraysExtraInfo&& from) noexcept
    : ArraysExtraInfo() {
    *this = ::std::move(from);
  }

  inline ArraysExtraInfo& operator=(ArraysExtraInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ArraysExtraInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArraysExtraInfo* internal_default_instance() {
    return reinterpret_cast<const ArraysExtraInfo*>(
               &_ArraysExtraInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ArraysExtraInfo* other);
  friend void swap(ArraysExtraInfo& a, ArraysExtraInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArraysExtraInfo* New() const final {
    return CreateMaybeMessage<ArraysExtraInfo>(NULL);
  }

  ArraysExtraInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArraysExtraInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ArraysExtraInfo& from);
  void MergeFrom(const ArraysExtraInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArraysExtraInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ArraysExtraInfo_Entry Entry;

  // accessors -------------------------------------------------------

  // repeated .toco.ArraysExtraInfo.Entry entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  ::toco::ArraysExtraInfo_Entry* mutable_entries(int index);
  ::google::protobuf::RepeatedPtrField< ::toco::ArraysExtraInfo_Entry >*
      mutable_entries();
  const ::toco::ArraysExtraInfo_Entry& entries(int index) const;
  ::toco::ArraysExtraInfo_Entry* add_entries();
  const ::google::protobuf::RepeatedPtrField< ::toco::ArraysExtraInfo_Entry >&
      entries() const;

  // @@protoc_insertion_point(class_scope:toco.ArraysExtraInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::toco::ArraysExtraInfo_Entry > entries_;
  friend struct ::protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ModelFlags_ModelCheck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toco.ModelFlags.ModelCheck) */ {
 public:
  ModelFlags_ModelCheck();
  virtual ~ModelFlags_ModelCheck();

  ModelFlags_ModelCheck(const ModelFlags_ModelCheck& from);

  inline ModelFlags_ModelCheck& operator=(const ModelFlags_ModelCheck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ModelFlags_ModelCheck(ModelFlags_ModelCheck&& from) noexcept
    : ModelFlags_ModelCheck() {
    *this = ::std::move(from);
  }

  inline ModelFlags_ModelCheck& operator=(ModelFlags_ModelCheck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModelFlags_ModelCheck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModelFlags_ModelCheck* internal_default_instance() {
    return reinterpret_cast<const ModelFlags_ModelCheck*>(
               &_ModelFlags_ModelCheck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ModelFlags_ModelCheck* other);
  friend void swap(ModelFlags_ModelCheck& a, ModelFlags_ModelCheck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ModelFlags_ModelCheck* New() const final {
    return CreateMaybeMessage<ModelFlags_ModelCheck>(NULL);
  }

  ModelFlags_ModelCheck* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ModelFlags_ModelCheck>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ModelFlags_ModelCheck& from);
  void MergeFrom(const ModelFlags_ModelCheck& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelFlags_ModelCheck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string count_type = 1 [default = "None"];
  bool has_count_type() const;
  void clear_count_type();
  static const int kCountTypeFieldNumber = 1;
  const ::std::string& count_type() const;
  void set_count_type(const ::std::string& value);
  #if LANG_CXX11
  void set_count_type(::std::string&& value);
  #endif
  void set_count_type(const char* value);
  void set_count_type(const char* value, size_t size);
  ::std::string* mutable_count_type();
  ::std::string* release_count_type();
  void set_allocated_count_type(::std::string* count_type);

  // optional int32 count_min = 2 [default = -1];
  bool has_count_min() const;
  void clear_count_min();
  static const int kCountMinFieldNumber = 2;
  ::google::protobuf::int32 count_min() const;
  void set_count_min(::google::protobuf::int32 value);

  // optional int32 count_max = 3 [default = -1];
  bool has_count_max() const;
  void clear_count_max();
  static const int kCountMaxFieldNumber = 3;
  ::google::protobuf::int32 count_max() const;
  void set_count_max(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:toco.ModelFlags.ModelCheck)
 private:
  void set_has_count_type();
  void clear_has_count_type();
  void set_has_count_min();
  void clear_has_count_min();
  void set_has_count_max();
  void clear_has_count_max();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  public:
  static ::google::protobuf::internal::ExplicitlyConstructed< ::std::string> _i_give_permission_to_break_this_code_default_count_type_;
  private:
  ::google::protobuf::internal::ArenaStringPtr count_type_;
  ::google::protobuf::int32 count_min_;
  ::google::protobuf::int32 count_max_;
  friend struct ::protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ModelFlags : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toco.ModelFlags) */ {
 public:
  ModelFlags();
  virtual ~ModelFlags();

  ModelFlags(const ModelFlags& from);

  inline ModelFlags& operator=(const ModelFlags& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ModelFlags(ModelFlags&& from) noexcept
    : ModelFlags() {
    *this = ::std::move(from);
  }

  inline ModelFlags& operator=(ModelFlags&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModelFlags& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModelFlags* internal_default_instance() {
    return reinterpret_cast<const ModelFlags*>(
               &_ModelFlags_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(ModelFlags* other);
  friend void swap(ModelFlags& a, ModelFlags& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ModelFlags* New() const final {
    return CreateMaybeMessage<ModelFlags>(NULL);
  }

  ModelFlags* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ModelFlags>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ModelFlags& from);
  void MergeFrom(const ModelFlags& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelFlags* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ModelFlags_ModelCheck ModelCheck;

  // accessors -------------------------------------------------------

  // repeated .toco.InputArray input_arrays = 1;
  int input_arrays_size() const;
  void clear_input_arrays();
  static const int kInputArraysFieldNumber = 1;
  ::toco::InputArray* mutable_input_arrays(int index);
  ::google::protobuf::RepeatedPtrField< ::toco::InputArray >*
      mutable_input_arrays();
  const ::toco::InputArray& input_arrays(int index) const;
  ::toco::InputArray* add_input_arrays();
  const ::google::protobuf::RepeatedPtrField< ::toco::InputArray >&
      input_arrays() const;

  // repeated string output_arrays = 2;
  int output_arrays_size() const;
  void clear_output_arrays();
  static const int kOutputArraysFieldNumber = 2;
  const ::std::string& output_arrays(int index) const;
  ::std::string* mutable_output_arrays(int index);
  void set_output_arrays(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_output_arrays(int index, ::std::string&& value);
  #endif
  void set_output_arrays(int index, const char* value);
  void set_output_arrays(int index, const char* value, size_t size);
  ::std::string* add_output_arrays();
  void add_output_arrays(const ::std::string& value);
  #if LANG_CXX11
  void add_output_arrays(::std::string&& value);
  #endif
  void add_output_arrays(const char* value);
  void add_output_arrays(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& output_arrays() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_output_arrays();

  // repeated .toco.RnnState rnn_states = 12;
  int rnn_states_size() const;
  void clear_rnn_states();
  static const int kRnnStatesFieldNumber = 12;
  ::toco::RnnState* mutable_rnn_states(int index);
  ::google::protobuf::RepeatedPtrField< ::toco::RnnState >*
      mutable_rnn_states();
  const ::toco::RnnState& rnn_states(int index) const;
  ::toco::RnnState* add_rnn_states();
  const ::google::protobuf::RepeatedPtrField< ::toco::RnnState >&
      rnn_states() const;

  // repeated .toco.ModelFlags.ModelCheck model_checks = 14;
  int model_checks_size() const;
  void clear_model_checks();
  static const int kModelChecksFieldNumber = 14;
  ::toco::ModelFlags_ModelCheck* mutable_model_checks(int index);
  ::google::protobuf::RepeatedPtrField< ::toco::ModelFlags_ModelCheck >*
      mutable_model_checks();
  const ::toco::ModelFlags_ModelCheck& model_checks(int index) const;
  ::toco::ModelFlags_ModelCheck* add_model_checks();
  const ::google::protobuf::RepeatedPtrField< ::toco::ModelFlags_ModelCheck >&
      model_checks() const;

  // optional .toco.ArraysExtraInfo arrays_extra_info = 18;
  bool has_arrays_extra_info() const;
  void clear_arrays_extra_info();
  static const int kArraysExtraInfoFieldNumber = 18;
  private:
  const ::toco::ArraysExtraInfo& _internal_arrays_extra_info() const;
  public:
  const ::toco::ArraysExtraInfo& arrays_extra_info() const;
  ::toco::ArraysExtraInfo* release_arrays_extra_info();
  ::toco::ArraysExtraInfo* mutable_arrays_extra_info();
  void set_allocated_arrays_extra_info(::toco::ArraysExtraInfo* arrays_extra_info);

  // optional bool variable_batch = 10;
  bool has_variable_batch() const;
  void clear_variable_batch();
  static const int kVariableBatchFieldNumber = 10;
  bool variable_batch() const;
  void set_variable_batch(bool value);

  // optional bool allow_nonexistent_arrays = 16;
  bool has_allow_nonexistent_arrays() const;
  void clear_allow_nonexistent_arrays();
  static const int kAllowNonexistentArraysFieldNumber = 16;
  bool allow_nonexistent_arrays() const;
  void set_allow_nonexistent_arrays(bool value);

  // optional bool allow_nonascii_arrays = 17;
  bool has_allow_nonascii_arrays() const;
  void clear_allow_nonascii_arrays();
  static const int kAllowNonasciiArraysFieldNumber = 17;
  bool allow_nonascii_arrays() const;
  void set_allow_nonascii_arrays(bool value);

  // optional bool change_concat_input_ranges = 19 [default = true];
  bool has_change_concat_input_ranges() const;
  void clear_change_concat_input_ranges();
  static const int kChangeConcatInputRangesFieldNumber = 19;
  bool change_concat_input_ranges() const;
  void set_change_concat_input_ranges(bool value);

  // @@protoc_insertion_point(class_scope:toco.ModelFlags)
 private:
  void set_has_variable_batch();
  void clear_has_variable_batch();
  void set_has_allow_nonexistent_arrays();
  void clear_has_allow_nonexistent_arrays();
  void set_has_allow_nonascii_arrays();
  void clear_has_allow_nonascii_arrays();
  void set_has_arrays_extra_info();
  void clear_has_arrays_extra_info();
  void set_has_change_concat_input_ranges();
  void clear_has_change_concat_input_ranges();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::toco::InputArray > input_arrays_;
  ::google::protobuf::RepeatedPtrField< ::std::string> output_arrays_;
  ::google::protobuf::RepeatedPtrField< ::toco::RnnState > rnn_states_;
  ::google::protobuf::RepeatedPtrField< ::toco::ModelFlags_ModelCheck > model_checks_;
  ::toco::ArraysExtraInfo* arrays_extra_info_;
  bool variable_batch_;
  bool allow_nonexistent_arrays_;
  bool allow_nonascii_arrays_;
  bool change_concat_input_ranges_;
  friend struct ::protobuf_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InputArrayShape

// repeated int32 dims = 2;
inline int InputArrayShape::dims_size() const {
  return dims_.size();
}
inline void InputArrayShape::clear_dims() {
  dims_.Clear();
}
inline ::google::protobuf::int32 InputArrayShape::dims(int index) const {
  // @@protoc_insertion_point(field_get:toco.InputArrayShape.dims)
  return dims_.Get(index);
}
inline void InputArrayShape::set_dims(int index, ::google::protobuf::int32 value) {
  dims_.Set(index, value);
  // @@protoc_insertion_point(field_set:toco.InputArrayShape.dims)
}
inline void InputArrayShape::add_dims(::google::protobuf::int32 value) {
  dims_.Add(value);
  // @@protoc_insertion_point(field_add:toco.InputArrayShape.dims)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
InputArrayShape::dims() const {
  // @@protoc_insertion_point(field_list:toco.InputArrayShape.dims)
  return dims_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
InputArrayShape::mutable_dims() {
  // @@protoc_insertion_point(field_mutable_list:toco.InputArrayShape.dims)
  return &dims_;
}

// -------------------------------------------------------------------

// InputArray

// optional string name = 1;
inline bool InputArray::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InputArray::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InputArray::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InputArray::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& InputArray::name() const {
  // @@protoc_insertion_point(field_get:toco.InputArray.name)
  return name_.GetNoArena();
}
inline void InputArray::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:toco.InputArray.name)
}
#if LANG_CXX11
inline void InputArray::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:toco.InputArray.name)
}
#endif
inline void InputArray::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:toco.InputArray.name)
}
inline void InputArray::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:toco.InputArray.name)
}
inline ::std::string* InputArray::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:toco.InputArray.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InputArray::release_name() {
  // @@protoc_insertion_point(field_release:toco.InputArray.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InputArray::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:toco.InputArray.name)
}

// optional .toco.InputArrayShape shape = 6;
inline bool InputArray::has_shape() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void InputArray::set_has_shape() {
  _has_bits_[0] |= 0x00000002u;
}
inline void InputArray::clear_has_shape() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void InputArray::clear_shape() {
  if (shape_ != NULL) shape_->Clear();
  clear_has_shape();
}
inline const ::toco::InputArrayShape& InputArray::_internal_shape() const {
  return *shape_;
}
inline const ::toco::InputArrayShape& InputArray::shape() const {
  const ::toco::InputArrayShape* p = shape_;
  // @@protoc_insertion_point(field_get:toco.InputArray.shape)
  return p != NULL ? *p : *reinterpret_cast<const ::toco::InputArrayShape*>(
      &::toco::_InputArrayShape_default_instance_);
}
inline ::toco::InputArrayShape* InputArray::release_shape() {
  // @@protoc_insertion_point(field_release:toco.InputArray.shape)
  clear_has_shape();
  ::toco::InputArrayShape* temp = shape_;
  shape_ = NULL;
  return temp;
}
inline ::toco::InputArrayShape* InputArray::mutable_shape() {
  set_has_shape();
  if (shape_ == NULL) {
    auto* p = CreateMaybeMessage<::toco::InputArrayShape>(GetArenaNoVirtual());
    shape_ = p;
  }
  // @@protoc_insertion_point(field_mutable:toco.InputArray.shape)
  return shape_;
}
inline void InputArray::set_allocated_shape(::toco::InputArrayShape* shape) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete shape_;
  }
  if (shape) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      shape = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, shape, submessage_arena);
    }
    set_has_shape();
  } else {
    clear_has_shape();
  }
  shape_ = shape;
  // @@protoc_insertion_point(field_set_allocated:toco.InputArray.shape)
}

// optional float mean_value = 3;
inline bool InputArray::has_mean_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void InputArray::set_has_mean_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void InputArray::clear_has_mean_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void InputArray::clear_mean_value() {
  mean_value_ = 0;
  clear_has_mean_value();
}
inline float InputArray::mean_value() const {
  // @@protoc_insertion_point(field_get:toco.InputArray.mean_value)
  return mean_value_;
}
inline void InputArray::set_mean_value(float value) {
  set_has_mean_value();
  mean_value_ = value;
  // @@protoc_insertion_point(field_set:toco.InputArray.mean_value)
}

// optional float std_value = 4 [default = 1];
inline bool InputArray::has_std_value() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void InputArray::set_has_std_value() {
  _has_bits_[0] |= 0x00000010u;
}
inline void InputArray::clear_has_std_value() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void InputArray::clear_std_value() {
  std_value_ = 1;
  clear_has_std_value();
}
inline float InputArray::std_value() const {
  // @@protoc_insertion_point(field_get:toco.InputArray.std_value)
  return std_value_;
}
inline void InputArray::set_std_value(float value) {
  set_has_std_value();
  std_value_ = value;
  // @@protoc_insertion_point(field_set:toco.InputArray.std_value)
}

// optional .toco.IODataType data_type = 5;
inline bool InputArray::has_data_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void InputArray::set_has_data_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void InputArray::clear_has_data_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void InputArray::clear_data_type() {
  data_type_ = 0;
  clear_has_data_type();
}
inline ::toco::IODataType InputArray::data_type() const {
  // @@protoc_insertion_point(field_get:toco.InputArray.data_type)
  return static_cast< ::toco::IODataType >(data_type_);
}
inline void InputArray::set_data_type(::toco::IODataType value) {
  assert(::toco::IODataType_IsValid(value));
  set_has_data_type();
  data_type_ = value;
  // @@protoc_insertion_point(field_set:toco.InputArray.data_type)
}

// -------------------------------------------------------------------

// RnnState

// optional string state_array = 1;
inline bool RnnState::has_state_array() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RnnState::set_has_state_array() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RnnState::clear_has_state_array() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RnnState::clear_state_array() {
  state_array_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_state_array();
}
inline const ::std::string& RnnState::state_array() const {
  // @@protoc_insertion_point(field_get:toco.RnnState.state_array)
  return state_array_.GetNoArena();
}
inline void RnnState::set_state_array(const ::std::string& value) {
  set_has_state_array();
  state_array_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:toco.RnnState.state_array)
}
#if LANG_CXX11
inline void RnnState::set_state_array(::std::string&& value) {
  set_has_state_array();
  state_array_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:toco.RnnState.state_array)
}
#endif
inline void RnnState::set_state_array(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_state_array();
  state_array_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:toco.RnnState.state_array)
}
inline void RnnState::set_state_array(const char* value, size_t size) {
  set_has_state_array();
  state_array_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:toco.RnnState.state_array)
}
inline ::std::string* RnnState::mutable_state_array() {
  set_has_state_array();
  // @@protoc_insertion_point(field_mutable:toco.RnnState.state_array)
  return state_array_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RnnState::release_state_array() {
  // @@protoc_insertion_point(field_release:toco.RnnState.state_array)
  if (!has_state_array()) {
    return NULL;
  }
  clear_has_state_array();
  return state_array_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RnnState::set_allocated_state_array(::std::string* state_array) {
  if (state_array != NULL) {
    set_has_state_array();
  } else {
    clear_has_state_array();
  }
  state_array_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), state_array);
  // @@protoc_insertion_point(field_set_allocated:toco.RnnState.state_array)
}

// optional string back_edge_source_array = 2;
inline bool RnnState::has_back_edge_source_array() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RnnState::set_has_back_edge_source_array() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RnnState::clear_has_back_edge_source_array() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RnnState::clear_back_edge_source_array() {
  back_edge_source_array_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_back_edge_source_array();
}
inline const ::std::string& RnnState::back_edge_source_array() const {
  // @@protoc_insertion_point(field_get:toco.RnnState.back_edge_source_array)
  return back_edge_source_array_.GetNoArena();
}
inline void RnnState::set_back_edge_source_array(const ::std::string& value) {
  set_has_back_edge_source_array();
  back_edge_source_array_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:toco.RnnState.back_edge_source_array)
}
#if LANG_CXX11
inline void RnnState::set_back_edge_source_array(::std::string&& value) {
  set_has_back_edge_source_array();
  back_edge_source_array_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:toco.RnnState.back_edge_source_array)
}
#endif
inline void RnnState::set_back_edge_source_array(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_back_edge_source_array();
  back_edge_source_array_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:toco.RnnState.back_edge_source_array)
}
inline void RnnState::set_back_edge_source_array(const char* value, size_t size) {
  set_has_back_edge_source_array();
  back_edge_source_array_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:toco.RnnState.back_edge_source_array)
}
inline ::std::string* RnnState::mutable_back_edge_source_array() {
  set_has_back_edge_source_array();
  // @@protoc_insertion_point(field_mutable:toco.RnnState.back_edge_source_array)
  return back_edge_source_array_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RnnState::release_back_edge_source_array() {
  // @@protoc_insertion_point(field_release:toco.RnnState.back_edge_source_array)
  if (!has_back_edge_source_array()) {
    return NULL;
  }
  clear_has_back_edge_source_array();
  return back_edge_source_array_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RnnState::set_allocated_back_edge_source_array(::std::string* back_edge_source_array) {
  if (back_edge_source_array != NULL) {
    set_has_back_edge_source_array();
  } else {
    clear_has_back_edge_source_array();
  }
  back_edge_source_array_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), back_edge_source_array);
  // @@protoc_insertion_point(field_set_allocated:toco.RnnState.back_edge_source_array)
}

// optional bool discardable = 5;
inline bool RnnState::has_discardable() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RnnState::set_has_discardable() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RnnState::clear_has_discardable() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RnnState::clear_discardable() {
  discardable_ = false;
  clear_has_discardable();
}
inline bool RnnState::discardable() const {
  // @@protoc_insertion_point(field_get:toco.RnnState.discardable)
  return discardable_;
}
inline void RnnState::set_discardable(bool value) {
  set_has_discardable();
  discardable_ = value;
  // @@protoc_insertion_point(field_set:toco.RnnState.discardable)
}

// optional int32 size = 3;
inline bool RnnState::has_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RnnState::set_has_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RnnState::clear_has_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RnnState::clear_size() {
  size_ = 0;
  clear_has_size();
}
inline ::google::protobuf::int32 RnnState::size() const {
  // @@protoc_insertion_point(field_get:toco.RnnState.size)
  return size_;
}
inline void RnnState::set_size(::google::protobuf::int32 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:toco.RnnState.size)
}

// -------------------------------------------------------------------

// ArraysExtraInfo_Entry

// optional string name = 1;
inline bool ArraysExtraInfo_Entry::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ArraysExtraInfo_Entry::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ArraysExtraInfo_Entry::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ArraysExtraInfo_Entry::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& ArraysExtraInfo_Entry::name() const {
  // @@protoc_insertion_point(field_get:toco.ArraysExtraInfo.Entry.name)
  return name_.GetNoArena();
}
inline void ArraysExtraInfo_Entry::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:toco.ArraysExtraInfo.Entry.name)
}
#if LANG_CXX11
inline void ArraysExtraInfo_Entry::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:toco.ArraysExtraInfo.Entry.name)
}
#endif
inline void ArraysExtraInfo_Entry::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:toco.ArraysExtraInfo.Entry.name)
}
inline void ArraysExtraInfo_Entry::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:toco.ArraysExtraInfo.Entry.name)
}
inline ::std::string* ArraysExtraInfo_Entry::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:toco.ArraysExtraInfo.Entry.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ArraysExtraInfo_Entry::release_name() {
  // @@protoc_insertion_point(field_release:toco.ArraysExtraInfo.Entry.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ArraysExtraInfo_Entry::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:toco.ArraysExtraInfo.Entry.name)
}

// optional string name_regexp = 7;
inline bool ArraysExtraInfo_Entry::has_name_regexp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ArraysExtraInfo_Entry::set_has_name_regexp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ArraysExtraInfo_Entry::clear_has_name_regexp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ArraysExtraInfo_Entry::clear_name_regexp() {
  name_regexp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name_regexp();
}
inline const ::std::string& ArraysExtraInfo_Entry::name_regexp() const {
  // @@protoc_insertion_point(field_get:toco.ArraysExtraInfo.Entry.name_regexp)
  return name_regexp_.GetNoArena();
}
inline void ArraysExtraInfo_Entry::set_name_regexp(const ::std::string& value) {
  set_has_name_regexp();
  name_regexp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:toco.ArraysExtraInfo.Entry.name_regexp)
}
#if LANG_CXX11
inline void ArraysExtraInfo_Entry::set_name_regexp(::std::string&& value) {
  set_has_name_regexp();
  name_regexp_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:toco.ArraysExtraInfo.Entry.name_regexp)
}
#endif
inline void ArraysExtraInfo_Entry::set_name_regexp(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name_regexp();
  name_regexp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:toco.ArraysExtraInfo.Entry.name_regexp)
}
inline void ArraysExtraInfo_Entry::set_name_regexp(const char* value, size_t size) {
  set_has_name_regexp();
  name_regexp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:toco.ArraysExtraInfo.Entry.name_regexp)
}
inline ::std::string* ArraysExtraInfo_Entry::mutable_name_regexp() {
  set_has_name_regexp();
  // @@protoc_insertion_point(field_mutable:toco.ArraysExtraInfo.Entry.name_regexp)
  return name_regexp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ArraysExtraInfo_Entry::release_name_regexp() {
  // @@protoc_insertion_point(field_release:toco.ArraysExtraInfo.Entry.name_regexp)
  if (!has_name_regexp()) {
    return NULL;
  }
  clear_has_name_regexp();
  return name_regexp_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ArraysExtraInfo_Entry::set_allocated_name_regexp(::std::string* name_regexp) {
  if (name_regexp != NULL) {
    set_has_name_regexp();
  } else {
    clear_has_name_regexp();
  }
  name_regexp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name_regexp);
  // @@protoc_insertion_point(field_set_allocated:toco.ArraysExtraInfo.Entry.name_regexp)
}

// optional double min = 2;
inline bool ArraysExtraInfo_Entry::has_min() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ArraysExtraInfo_Entry::set_has_min() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ArraysExtraInfo_Entry::clear_has_min() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ArraysExtraInfo_Entry::clear_min() {
  min_ = 0;
  clear_has_min();
}
inline double ArraysExtraInfo_Entry::min() const {
  // @@protoc_insertion_point(field_get:toco.ArraysExtraInfo.Entry.min)
  return min_;
}
inline void ArraysExtraInfo_Entry::set_min(double value) {
  set_has_min();
  min_ = value;
  // @@protoc_insertion_point(field_set:toco.ArraysExtraInfo.Entry.min)
}

// optional double max = 3;
inline bool ArraysExtraInfo_Entry::has_max() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ArraysExtraInfo_Entry::set_has_max() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ArraysExtraInfo_Entry::clear_has_max() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ArraysExtraInfo_Entry::clear_max() {
  max_ = 0;
  clear_has_max();
}
inline double ArraysExtraInfo_Entry::max() const {
  // @@protoc_insertion_point(field_get:toco.ArraysExtraInfo.Entry.max)
  return max_;
}
inline void ArraysExtraInfo_Entry::set_max(double value) {
  set_has_max();
  max_ = value;
  // @@protoc_insertion_point(field_set:toco.ArraysExtraInfo.Entry.max)
}

// optional .toco.IODataType data_type = 4;
inline bool ArraysExtraInfo_Entry::has_data_type() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ArraysExtraInfo_Entry::set_has_data_type() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ArraysExtraInfo_Entry::clear_has_data_type() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ArraysExtraInfo_Entry::clear_data_type() {
  data_type_ = 0;
  clear_has_data_type();
}
inline ::toco::IODataType ArraysExtraInfo_Entry::data_type() const {
  // @@protoc_insertion_point(field_get:toco.ArraysExtraInfo.Entry.data_type)
  return static_cast< ::toco::IODataType >(data_type_);
}
inline void ArraysExtraInfo_Entry::set_data_type(::toco::IODataType value) {
  assert(::toco::IODataType_IsValid(value));
  set_has_data_type();
  data_type_ = value;
  // @@protoc_insertion_point(field_set:toco.ArraysExtraInfo.Entry.data_type)
}

// optional .toco.InputArrayShape shape = 5;
inline bool ArraysExtraInfo_Entry::has_shape() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ArraysExtraInfo_Entry::set_has_shape() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ArraysExtraInfo_Entry::clear_has_shape() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ArraysExtraInfo_Entry::clear_shape() {
  if (shape_ != NULL) shape_->Clear();
  clear_has_shape();
}
inline const ::toco::InputArrayShape& ArraysExtraInfo_Entry::_internal_shape() const {
  return *shape_;
}
inline const ::toco::InputArrayShape& ArraysExtraInfo_Entry::shape() const {
  const ::toco::InputArrayShape* p = shape_;
  // @@protoc_insertion_point(field_get:toco.ArraysExtraInfo.Entry.shape)
  return p != NULL ? *p : *reinterpret_cast<const ::toco::InputArrayShape*>(
      &::toco::_InputArrayShape_default_instance_);
}
inline ::toco::InputArrayShape* ArraysExtraInfo_Entry::release_shape() {
  // @@protoc_insertion_point(field_release:toco.ArraysExtraInfo.Entry.shape)
  clear_has_shape();
  ::toco::InputArrayShape* temp = shape_;
  shape_ = NULL;
  return temp;
}
inline ::toco::InputArrayShape* ArraysExtraInfo_Entry::mutable_shape() {
  set_has_shape();
  if (shape_ == NULL) {
    auto* p = CreateMaybeMessage<::toco::InputArrayShape>(GetArenaNoVirtual());
    shape_ = p;
  }
  // @@protoc_insertion_point(field_mutable:toco.ArraysExtraInfo.Entry.shape)
  return shape_;
}
inline void ArraysExtraInfo_Entry::set_allocated_shape(::toco::InputArrayShape* shape) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete shape_;
  }
  if (shape) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      shape = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, shape, submessage_arena);
    }
    set_has_shape();
  } else {
    clear_has_shape();
  }
  shape_ = shape;
  // @@protoc_insertion_point(field_set_allocated:toco.ArraysExtraInfo.Entry.shape)
}

// optional float constant_float_value = 6;
inline bool ArraysExtraInfo_Entry::has_constant_float_value() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ArraysExtraInfo_Entry::set_has_constant_float_value() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ArraysExtraInfo_Entry::clear_has_constant_float_value() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ArraysExtraInfo_Entry::clear_constant_float_value() {
  constant_float_value_ = 0;
  clear_has_constant_float_value();
}
inline float ArraysExtraInfo_Entry::constant_float_value() const {
  // @@protoc_insertion_point(field_get:toco.ArraysExtraInfo.Entry.constant_float_value)
  return constant_float_value_;
}
inline void ArraysExtraInfo_Entry::set_constant_float_value(float value) {
  set_has_constant_float_value();
  constant_float_value_ = value;
  // @@protoc_insertion_point(field_set:toco.ArraysExtraInfo.Entry.constant_float_value)
}

// -------------------------------------------------------------------

// ArraysExtraInfo

// repeated .toco.ArraysExtraInfo.Entry entries = 1;
inline int ArraysExtraInfo::entries_size() const {
  return entries_.size();
}
inline void ArraysExtraInfo::clear_entries() {
  entries_.Clear();
}
inline ::toco::ArraysExtraInfo_Entry* ArraysExtraInfo::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:toco.ArraysExtraInfo.entries)
  return entries_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::toco::ArraysExtraInfo_Entry >*
ArraysExtraInfo::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:toco.ArraysExtraInfo.entries)
  return &entries_;
}
inline const ::toco::ArraysExtraInfo_Entry& ArraysExtraInfo::entries(int index) const {
  // @@protoc_insertion_point(field_get:toco.ArraysExtraInfo.entries)
  return entries_.Get(index);
}
inline ::toco::ArraysExtraInfo_Entry* ArraysExtraInfo::add_entries() {
  // @@protoc_insertion_point(field_add:toco.ArraysExtraInfo.entries)
  return entries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::toco::ArraysExtraInfo_Entry >&
ArraysExtraInfo::entries() const {
  // @@protoc_insertion_point(field_list:toco.ArraysExtraInfo.entries)
  return entries_;
}

// -------------------------------------------------------------------

// ModelFlags_ModelCheck

// optional string count_type = 1 [default = "None"];
inline bool ModelFlags_ModelCheck::has_count_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModelFlags_ModelCheck::set_has_count_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModelFlags_ModelCheck::clear_has_count_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModelFlags_ModelCheck::clear_count_type() {
  count_type_.ClearToDefaultNoArena(&::toco::ModelFlags_ModelCheck::_i_give_permission_to_break_this_code_default_count_type_.get());
  clear_has_count_type();
}
inline const ::std::string& ModelFlags_ModelCheck::count_type() const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.ModelCheck.count_type)
  return count_type_.GetNoArena();
}
inline void ModelFlags_ModelCheck::set_count_type(const ::std::string& value) {
  set_has_count_type();
  count_type_.SetNoArena(&::toco::ModelFlags_ModelCheck::_i_give_permission_to_break_this_code_default_count_type_.get(), value);
  // @@protoc_insertion_point(field_set:toco.ModelFlags.ModelCheck.count_type)
}
#if LANG_CXX11
inline void ModelFlags_ModelCheck::set_count_type(::std::string&& value) {
  set_has_count_type();
  count_type_.SetNoArena(
    &::toco::ModelFlags_ModelCheck::_i_give_permission_to_break_this_code_default_count_type_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:toco.ModelFlags.ModelCheck.count_type)
}
#endif
inline void ModelFlags_ModelCheck::set_count_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_count_type();
  count_type_.SetNoArena(&::toco::ModelFlags_ModelCheck::_i_give_permission_to_break_this_code_default_count_type_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:toco.ModelFlags.ModelCheck.count_type)
}
inline void ModelFlags_ModelCheck::set_count_type(const char* value, size_t size) {
  set_has_count_type();
  count_type_.SetNoArena(&::toco::ModelFlags_ModelCheck::_i_give_permission_to_break_this_code_default_count_type_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:toco.ModelFlags.ModelCheck.count_type)
}
inline ::std::string* ModelFlags_ModelCheck::mutable_count_type() {
  set_has_count_type();
  // @@protoc_insertion_point(field_mutable:toco.ModelFlags.ModelCheck.count_type)
  return count_type_.MutableNoArena(&::toco::ModelFlags_ModelCheck::_i_give_permission_to_break_this_code_default_count_type_.get());
}
inline ::std::string* ModelFlags_ModelCheck::release_count_type() {
  // @@protoc_insertion_point(field_release:toco.ModelFlags.ModelCheck.count_type)
  if (!has_count_type()) {
    return NULL;
  }
  clear_has_count_type();
  return count_type_.ReleaseNonDefaultNoArena(&::toco::ModelFlags_ModelCheck::_i_give_permission_to_break_this_code_default_count_type_.get());
}
inline void ModelFlags_ModelCheck::set_allocated_count_type(::std::string* count_type) {
  if (count_type != NULL) {
    set_has_count_type();
  } else {
    clear_has_count_type();
  }
  count_type_.SetAllocatedNoArena(&::toco::ModelFlags_ModelCheck::_i_give_permission_to_break_this_code_default_count_type_.get(), count_type);
  // @@protoc_insertion_point(field_set_allocated:toco.ModelFlags.ModelCheck.count_type)
}

// optional int32 count_min = 2 [default = -1];
inline bool ModelFlags_ModelCheck::has_count_min() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ModelFlags_ModelCheck::set_has_count_min() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ModelFlags_ModelCheck::clear_has_count_min() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ModelFlags_ModelCheck::clear_count_min() {
  count_min_ = -1;
  clear_has_count_min();
}
inline ::google::protobuf::int32 ModelFlags_ModelCheck::count_min() const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.ModelCheck.count_min)
  return count_min_;
}
inline void ModelFlags_ModelCheck::set_count_min(::google::protobuf::int32 value) {
  set_has_count_min();
  count_min_ = value;
  // @@protoc_insertion_point(field_set:toco.ModelFlags.ModelCheck.count_min)
}

// optional int32 count_max = 3 [default = -1];
inline bool ModelFlags_ModelCheck::has_count_max() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ModelFlags_ModelCheck::set_has_count_max() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ModelFlags_ModelCheck::clear_has_count_max() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ModelFlags_ModelCheck::clear_count_max() {
  count_max_ = -1;
  clear_has_count_max();
}
inline ::google::protobuf::int32 ModelFlags_ModelCheck::count_max() const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.ModelCheck.count_max)
  return count_max_;
}
inline void ModelFlags_ModelCheck::set_count_max(::google::protobuf::int32 value) {
  set_has_count_max();
  count_max_ = value;
  // @@protoc_insertion_point(field_set:toco.ModelFlags.ModelCheck.count_max)
}

// -------------------------------------------------------------------

// ModelFlags

// repeated .toco.InputArray input_arrays = 1;
inline int ModelFlags::input_arrays_size() const {
  return input_arrays_.size();
}
inline void ModelFlags::clear_input_arrays() {
  input_arrays_.Clear();
}
inline ::toco::InputArray* ModelFlags::mutable_input_arrays(int index) {
  // @@protoc_insertion_point(field_mutable:toco.ModelFlags.input_arrays)
  return input_arrays_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::toco::InputArray >*
ModelFlags::mutable_input_arrays() {
  // @@protoc_insertion_point(field_mutable_list:toco.ModelFlags.input_arrays)
  return &input_arrays_;
}
inline const ::toco::InputArray& ModelFlags::input_arrays(int index) const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.input_arrays)
  return input_arrays_.Get(index);
}
inline ::toco::InputArray* ModelFlags::add_input_arrays() {
  // @@protoc_insertion_point(field_add:toco.ModelFlags.input_arrays)
  return input_arrays_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::toco::InputArray >&
ModelFlags::input_arrays() const {
  // @@protoc_insertion_point(field_list:toco.ModelFlags.input_arrays)
  return input_arrays_;
}

// repeated string output_arrays = 2;
inline int ModelFlags::output_arrays_size() const {
  return output_arrays_.size();
}
inline void ModelFlags::clear_output_arrays() {
  output_arrays_.Clear();
}
inline const ::std::string& ModelFlags::output_arrays(int index) const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.output_arrays)
  return output_arrays_.Get(index);
}
inline ::std::string* ModelFlags::mutable_output_arrays(int index) {
  // @@protoc_insertion_point(field_mutable:toco.ModelFlags.output_arrays)
  return output_arrays_.Mutable(index);
}
inline void ModelFlags::set_output_arrays(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:toco.ModelFlags.output_arrays)
  output_arrays_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ModelFlags::set_output_arrays(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:toco.ModelFlags.output_arrays)
  output_arrays_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ModelFlags::set_output_arrays(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  output_arrays_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:toco.ModelFlags.output_arrays)
}
inline void ModelFlags::set_output_arrays(int index, const char* value, size_t size) {
  output_arrays_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:toco.ModelFlags.output_arrays)
}
inline ::std::string* ModelFlags::add_output_arrays() {
  // @@protoc_insertion_point(field_add_mutable:toco.ModelFlags.output_arrays)
  return output_arrays_.Add();
}
inline void ModelFlags::add_output_arrays(const ::std::string& value) {
  output_arrays_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:toco.ModelFlags.output_arrays)
}
#if LANG_CXX11
inline void ModelFlags::add_output_arrays(::std::string&& value) {
  output_arrays_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:toco.ModelFlags.output_arrays)
}
#endif
inline void ModelFlags::add_output_arrays(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  output_arrays_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:toco.ModelFlags.output_arrays)
}
inline void ModelFlags::add_output_arrays(const char* value, size_t size) {
  output_arrays_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:toco.ModelFlags.output_arrays)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ModelFlags::output_arrays() const {
  // @@protoc_insertion_point(field_list:toco.ModelFlags.output_arrays)
  return output_arrays_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ModelFlags::mutable_output_arrays() {
  // @@protoc_insertion_point(field_mutable_list:toco.ModelFlags.output_arrays)
  return &output_arrays_;
}

// optional bool variable_batch = 10;
inline bool ModelFlags::has_variable_batch() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ModelFlags::set_has_variable_batch() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ModelFlags::clear_has_variable_batch() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ModelFlags::clear_variable_batch() {
  variable_batch_ = false;
  clear_has_variable_batch();
}
inline bool ModelFlags::variable_batch() const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.variable_batch)
  return variable_batch_;
}
inline void ModelFlags::set_variable_batch(bool value) {
  set_has_variable_batch();
  variable_batch_ = value;
  // @@protoc_insertion_point(field_set:toco.ModelFlags.variable_batch)
}

// repeated .toco.RnnState rnn_states = 12;
inline int ModelFlags::rnn_states_size() const {
  return rnn_states_.size();
}
inline void ModelFlags::clear_rnn_states() {
  rnn_states_.Clear();
}
inline ::toco::RnnState* ModelFlags::mutable_rnn_states(int index) {
  // @@protoc_insertion_point(field_mutable:toco.ModelFlags.rnn_states)
  return rnn_states_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::toco::RnnState >*
ModelFlags::mutable_rnn_states() {
  // @@protoc_insertion_point(field_mutable_list:toco.ModelFlags.rnn_states)
  return &rnn_states_;
}
inline const ::toco::RnnState& ModelFlags::rnn_states(int index) const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.rnn_states)
  return rnn_states_.Get(index);
}
inline ::toco::RnnState* ModelFlags::add_rnn_states() {
  // @@protoc_insertion_point(field_add:toco.ModelFlags.rnn_states)
  return rnn_states_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::toco::RnnState >&
ModelFlags::rnn_states() const {
  // @@protoc_insertion_point(field_list:toco.ModelFlags.rnn_states)
  return rnn_states_;
}

// repeated .toco.ModelFlags.ModelCheck model_checks = 14;
inline int ModelFlags::model_checks_size() const {
  return model_checks_.size();
}
inline void ModelFlags::clear_model_checks() {
  model_checks_.Clear();
}
inline ::toco::ModelFlags_ModelCheck* ModelFlags::mutable_model_checks(int index) {
  // @@protoc_insertion_point(field_mutable:toco.ModelFlags.model_checks)
  return model_checks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::toco::ModelFlags_ModelCheck >*
ModelFlags::mutable_model_checks() {
  // @@protoc_insertion_point(field_mutable_list:toco.ModelFlags.model_checks)
  return &model_checks_;
}
inline const ::toco::ModelFlags_ModelCheck& ModelFlags::model_checks(int index) const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.model_checks)
  return model_checks_.Get(index);
}
inline ::toco::ModelFlags_ModelCheck* ModelFlags::add_model_checks() {
  // @@protoc_insertion_point(field_add:toco.ModelFlags.model_checks)
  return model_checks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::toco::ModelFlags_ModelCheck >&
ModelFlags::model_checks() const {
  // @@protoc_insertion_point(field_list:toco.ModelFlags.model_checks)
  return model_checks_;
}

// optional bool allow_nonexistent_arrays = 16;
inline bool ModelFlags::has_allow_nonexistent_arrays() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ModelFlags::set_has_allow_nonexistent_arrays() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ModelFlags::clear_has_allow_nonexistent_arrays() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ModelFlags::clear_allow_nonexistent_arrays() {
  allow_nonexistent_arrays_ = false;
  clear_has_allow_nonexistent_arrays();
}
inline bool ModelFlags::allow_nonexistent_arrays() const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.allow_nonexistent_arrays)
  return allow_nonexistent_arrays_;
}
inline void ModelFlags::set_allow_nonexistent_arrays(bool value) {
  set_has_allow_nonexistent_arrays();
  allow_nonexistent_arrays_ = value;
  // @@protoc_insertion_point(field_set:toco.ModelFlags.allow_nonexistent_arrays)
}

// optional bool allow_nonascii_arrays = 17;
inline bool ModelFlags::has_allow_nonascii_arrays() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ModelFlags::set_has_allow_nonascii_arrays() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ModelFlags::clear_has_allow_nonascii_arrays() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ModelFlags::clear_allow_nonascii_arrays() {
  allow_nonascii_arrays_ = false;
  clear_has_allow_nonascii_arrays();
}
inline bool ModelFlags::allow_nonascii_arrays() const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.allow_nonascii_arrays)
  return allow_nonascii_arrays_;
}
inline void ModelFlags::set_allow_nonascii_arrays(bool value) {
  set_has_allow_nonascii_arrays();
  allow_nonascii_arrays_ = value;
  // @@protoc_insertion_point(field_set:toco.ModelFlags.allow_nonascii_arrays)
}

// optional .toco.ArraysExtraInfo arrays_extra_info = 18;
inline bool ModelFlags::has_arrays_extra_info() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModelFlags::set_has_arrays_extra_info() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModelFlags::clear_has_arrays_extra_info() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModelFlags::clear_arrays_extra_info() {
  if (arrays_extra_info_ != NULL) arrays_extra_info_->Clear();
  clear_has_arrays_extra_info();
}
inline const ::toco::ArraysExtraInfo& ModelFlags::_internal_arrays_extra_info() const {
  return *arrays_extra_info_;
}
inline const ::toco::ArraysExtraInfo& ModelFlags::arrays_extra_info() const {
  const ::toco::ArraysExtraInfo* p = arrays_extra_info_;
  // @@protoc_insertion_point(field_get:toco.ModelFlags.arrays_extra_info)
  return p != NULL ? *p : *reinterpret_cast<const ::toco::ArraysExtraInfo*>(
      &::toco::_ArraysExtraInfo_default_instance_);
}
inline ::toco::ArraysExtraInfo* ModelFlags::release_arrays_extra_info() {
  // @@protoc_insertion_point(field_release:toco.ModelFlags.arrays_extra_info)
  clear_has_arrays_extra_info();
  ::toco::ArraysExtraInfo* temp = arrays_extra_info_;
  arrays_extra_info_ = NULL;
  return temp;
}
inline ::toco::ArraysExtraInfo* ModelFlags::mutable_arrays_extra_info() {
  set_has_arrays_extra_info();
  if (arrays_extra_info_ == NULL) {
    auto* p = CreateMaybeMessage<::toco::ArraysExtraInfo>(GetArenaNoVirtual());
    arrays_extra_info_ = p;
  }
  // @@protoc_insertion_point(field_mutable:toco.ModelFlags.arrays_extra_info)
  return arrays_extra_info_;
}
inline void ModelFlags::set_allocated_arrays_extra_info(::toco::ArraysExtraInfo* arrays_extra_info) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete arrays_extra_info_;
  }
  if (arrays_extra_info) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      arrays_extra_info = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, arrays_extra_info, submessage_arena);
    }
    set_has_arrays_extra_info();
  } else {
    clear_has_arrays_extra_info();
  }
  arrays_extra_info_ = arrays_extra_info;
  // @@protoc_insertion_point(field_set_allocated:toco.ModelFlags.arrays_extra_info)
}

// optional bool change_concat_input_ranges = 19 [default = true];
inline bool ModelFlags::has_change_concat_input_ranges() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ModelFlags::set_has_change_concat_input_ranges() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ModelFlags::clear_has_change_concat_input_ranges() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ModelFlags::clear_change_concat_input_ranges() {
  change_concat_input_ranges_ = true;
  clear_has_change_concat_input_ranges();
}
inline bool ModelFlags::change_concat_input_ranges() const {
  // @@protoc_insertion_point(field_get:toco.ModelFlags.change_concat_input_ranges)
  return change_concat_input_ranges_;
}
inline void ModelFlags::set_change_concat_input_ranges(bool value) {
  set_has_change_concat_input_ranges();
  change_concat_input_ranges_ = value;
  // @@protoc_insertion_point(field_set:toco.ModelFlags.change_concat_input_ranges)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace toco

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_tensorflow_2fcontrib_2flite_2ftoco_2fmodel_5fflags_2eproto
